name = "Shear"
author = "BlueSheep2804"
version = "21.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ccab7fca08fa8190aad2e7ee395e67f196d8029ef4e4ff3943134f379be23552"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
