name = "Shear"
author = "BlueSheep2804"
version = "21.4.2-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3052a489a049069e7d428db3e18d41cae7f20a81a0548c77baf5fb5478e6f047"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
