name = "Shear"
author = "BlueSheep2804"
version = "21.4.1-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b59867847b494af743482308d108afa81ebf3bc2c0166ff544e93fdd755514b"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
