name = "Shear"
author = "BlueSheep2804"
version = "21.4.4-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61aa50c73597f31b705101bec6b34d415895d23bb9c15c327e0b65ed59260d43"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
