name = "Shear"
author = "BlueSheep2804"
version = "21.4.4-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c01d538b3c691fcdea478a8daf0fb0f433f0da75882cf970a806683ac649e4e7"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
