name = "Shear"
author = "BlueSheep2804"
version = "21.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66d47a85116e51636c999134eb3311a08ad490bba1dc22f87bc170070e7f92cf"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
