name = "Shear"
author = "BlueSheep2804"
version = "21.4.2-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb43ccba83ff920778c4f4e39630fd7595ddfd3d51522b4007a21be745f3e4f4"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
