name = "Shear"
author = "BlueSheep2804"
version = "21.4.3-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f15217b61eedec4037dc1e45586fe1c4ce5961a441e7e7a93ee6cdd5d17bde4c"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
