name = "Shear"
author = "BlueSheep2804"
version = "21.4.3-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1dc28ebddeeda46e99cee6966188376d39bcb7d26bfff7ebbe2e7f2486712db"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
