name = "Shear"
author = "BlueSheep2804"
version = "21.4.3-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a440a102fc7e9294951736cb3d473f509f475fdcfca2b1d0c098fc52f7f36cf"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
