name = "Shear"
author = "BlueSheep2804"
version = "21.7.1-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b346aea7693de9c197f9db4d0cd8255b4f0ed3ede5edb8124481589fd8d351e"

[versions]
fabric = "0.16.14"
minecraft = "1.21.7"

[options]
acceptable-game-versions = ["1.21.6"]
