name = "Shear"
author = "BlueSheep2804"
version = "21.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e2c8af8568ebca91d1320a900c51e1917241f6d540c02b14631acaf4b3357b5"

[versions]
fabric = "0.16.14"
minecraft = "1.21.7"

[options]
acceptable-game-versions = ["1.21.6"]
