name = "Shear"
author = "BlueSheep2804"
version = "21.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc0ac84c2c7221640b7c51feb1de42d3e56cb50ea60ade62143dfb141e07bf61"

[versions]
fabric = "0.16.14"
minecraft = "1.21.7"

[options]
acceptable-game-versions = ["1.21.6"]
