name = "Shear"
author = "BlueSheep2804"
version = "21.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3eb3326735d1ca7ee2e7c02f213856c34e9ab3f8fb7226154b41871d04e30106"

[versions]
fabric = "0.16.14"
minecraft = "1.21.7"

[options]
acceptable-game-versions = ["1.21.6"]
